// Mirrors backend/src/modules/rbac/permissions.catalog.ts — keep slugs in sync. This file
// only needs the slugs (for typed usage in components); the human-readable name/description/
// group used by the Role editor UI comes from the live GET /admin/permissions response instead
// of being duplicated here, since that's the one place that needs the full catalog shape.

export const PERMISSIONS = {
  products: ["view", "create", "update", "delete", "publish"].map((a) => `products.${a}`),
  productImages: ["manage"].map((a) => `product_images.${a}`),
  categories: ["view", "create", "update", "delete"].map((a) => `categories.${a}`),
  colors: ["view", "create", "update", "delete"].map((a) => `colors.${a}`),
  inventory: ["view", "update", "adjust"].map((a) => `inventory.${a}`),
  orders: ["view", "update", "cancel", "refund", "export"].map((a) => `orders.${a}`),
  coupons: ["view", "create", "update", "delete"].map((a) => `coupons.${a}`),
  customers: ["view", "update", "delete"].map((a) => `customers.${a}`),
  content: ["view", "create", "update", "delete"].map((a) => `content.${a}`),
  banners: ["view", "create", "update", "delete"].map((a) => `banners.${a}`),
  reviews: ["view", "update", "delete"].map((a) => `reviews.${a}`),
  emails: ["view", "update"].map((a) => `emails.${a}`),
  users: ["view", "create", "update", "delete", "assign_role"].map((a) => `users.${a}`),
  roles: ["view", "create", "update", "delete", "assign_permissions"].map((a) => `roles.${a}`),
  settings: ["view", "update"].map((a) => `settings.${a}`),
  auditLogs: ["view"].map((a) => `audit_logs.${a}`),
  analytics: ["view", "export"].map((a) => `analytics.${a}`),
} as const

/** Type-level convenience — not exhaustive-checked against the backend, just documents the
 * common ones used directly in JSX (e.g. `<Can permission={P.PRODUCTS_DELETE}>`). Any slug
 * string works with usePermission/Can even if it isn't listed here. */
export const P = {
  PRODUCTS_VIEW: "products.view",
  PRODUCTS_CREATE: "products.create",
  PRODUCTS_UPDATE: "products.update",
  PRODUCTS_DELETE: "products.delete",
  PRODUCTS_PUBLISH: "products.publish",
  PRODUCT_IMAGES_MANAGE: "product_images.manage",
  CATEGORIES_VIEW: "categories.view",
  CATEGORIES_CREATE: "categories.create",
  CATEGORIES_UPDATE: "categories.update",
  CATEGORIES_DELETE: "categories.delete",
  COLORS_VIEW: "colors.view",
  COLORS_CREATE: "colors.create",
  COLORS_UPDATE: "colors.update",
  COLORS_DELETE: "colors.delete",
  INVENTORY_VIEW: "inventory.view",
  INVENTORY_UPDATE: "inventory.update",
  ORDERS_VIEW: "orders.view",
  ORDERS_UPDATE: "orders.update",
  ORDERS_CANCEL: "orders.cancel",
  ORDERS_REFUND: "orders.refund",
  COUPONS_VIEW: "coupons.view",
  COUPONS_CREATE: "coupons.create",
  COUPONS_UPDATE: "coupons.update",
  COUPONS_DELETE: "coupons.delete",
  CUSTOMERS_VIEW: "customers.view",
  CUSTOMERS_UPDATE: "customers.update",
  CUSTOMERS_DELETE: "customers.delete",
  CONTENT_VIEW: "content.view",
  CONTENT_CREATE: "content.create",
  CONTENT_UPDATE: "content.update",
  CONTENT_DELETE: "content.delete",
  BANNERS_VIEW: "banners.view",
  BANNERS_CREATE: "banners.create",
  BANNERS_UPDATE: "banners.update",
  BANNERS_DELETE: "banners.delete",
  REVIEWS_VIEW: "reviews.view",
  REVIEWS_UPDATE: "reviews.update",
  REVIEWS_DELETE: "reviews.delete",
  EMAILS_VIEW: "emails.view",
  EMAILS_UPDATE: "emails.update",
  USERS_VIEW: "users.view",
  USERS_CREATE: "users.create",
  USERS_UPDATE: "users.update",
  USERS_DELETE: "users.delete",
  USERS_ASSIGN_ROLE: "users.assign_role",
  ROLES_VIEW: "roles.view",
  ROLES_CREATE: "roles.create",
  ROLES_UPDATE: "roles.update",
  ROLES_DELETE: "roles.delete",
  ROLES_ASSIGN_PERMISSIONS: "roles.assign_permissions",
  SETTINGS_VIEW: "settings.view",
  SETTINGS_UPDATE: "settings.update",
  AUDIT_LOGS_VIEW: "audit_logs.view",
  ANALYTICS_VIEW: "analytics.view",
  ANALYTICS_EXPORT: "analytics.export",
} as const

export type PermissionSlug = (typeof P)[keyof typeof P] | (string & {})
